### ISSUE TITLE
compiled binary needed

### ISSUE THREAD

**Issue by kn00tcn** [MrShoenel/HDD-Ping#1]
that or tell me what i need to compile (is it visual studio .NET? 4.5? free?)

**Comment by kn00tcn** [comment]
well i tried this https://keepalivehd.codeplex.com/ & it seems to work fine

i still dont get why a file has to be written, because with hdtune, the drive doesnt park during benchmarks or smart readings, so cant tools merely ping the drive?

**Comment by kn00tcn** [comment]
http://www.hydrogenaud.io/forums/index.php?showtopic=106298&view=findpost&p=869561 ooh this one's interesting, stuck in a cmd window though

i'm not sure a 0byte file counts as writing, but i do hear the heats doing something & performance monitor calls it writing... hmm

when i modified the script to remove the 0 byte file, the head parked unfortunately

**Comment by MrShoenel** [comment]
Yes, it target .NET 4.5. I built it using VS2012 back then. Do you still need the binaries?

**Comment by kn00tcn** [comment]
sure, i wouldnt mind comparing your tool (inb4 virus)

**Comment by MrShoenel** [comment]
Here's a link to the binary: https://goo.gl/Lp0tUH

**Comment by kn00tcn** [comment]
welp... i need pinging at max 8 seconds & minimum 1 second, yours is minimum 1 minute it seems

maybe i should just set up a dev environment to alter the code as i want (or use the other tools)

i think my drive warranty ends in a few months so by then i'll take them out of their enclosures, plug into sata, run wdidle to alter the timeout length in the firmware directly
